palette = 0=#494D64
palette = 1=#ED8796
palette = 2=#A6DA95
palette = 3=#EED49F
palette = 4=#8AADF4
palette = 5=#C6A0F6
palette = 6=#8BD5CA
palette = 7=#B8C0E0
palette = 8=#5B6078
palette = 9=#ED8796
palette = 10=#A6DA95
palette = 11=#EED49F
palette = 12=#8AADF4
palette = 13=#C6A0F6
palette = 14=#8BD5CA
palette = 15=#CAD3F5
background = #24273A
foreground = #CAD3F5
cursor-color = #F4DBD6
selection-background = #494D64
selection-foreground = #CAD3F5
