set -g mode-style "bg=default,fg=default,reverse"
set -g message-style "fg=#CAD3F5,bg=#24273A"
set -g message-command-style "fg=#CAD3F5,bg=#24273A"
set -g status-style "fg=#CAD3F5,bg=#24273A"
set -g status-left-style "fg=#8087A2,bg=#24273A"
set -g status-right "#{?pane_in_mode,#[fg=#24273A#,bg=#EED49F#,bold] SCROLL #[default],}#{?client_prefix,#[fg=#24273A#,bg=#A6DA95#,bold] PREFIX #[default],}#{?window_zoomed_flag,#[fg=#24273A#,bg=#8AADF4#,bold] ZOOM #[default],}#[fg=#8087A2] #h "
set -g window-status-style "fg=#8087A2,bg=#24273A"
set -g window-status-current-style "fg=#A6DA95,bg=#24273A"
set -g window-status-activity-style "fg=#24273A,bg=#EED49F"
set -g window-status-bell-style "fg=#24273A,bg=#ED8796"
set -g pane-border-style "fg=#8087A2"
set -g pane-active-border-style "fg=#A6DA95"
setw -g clock-mode-colour "#A6DA95"
