palette = 0=#45475A
palette = 1=#F38BA8
palette = 2=#A6E3A1
palette = 3=#F9E2AF
palette = 4=#89B4FA
palette = 5=#CBA6F7
palette = 6=#94E2D5
palette = 7=#BAC2DE
palette = 8=#585B70
palette = 9=#F38BA8
palette = 10=#A6E3A1
palette = 11=#F9E2AF
palette = 12=#89B4FA
palette = 13=#CBA6F7
palette = 14=#94E2D5
palette = 15=#CDD6F4
background = #1E1E2E
foreground = #CDD6F4
cursor-color = #F5E0DC
selection-background = #45475A
selection-foreground = #CDD6F4
