set -g mode-style "bg=default,fg=default,reverse"
set -g message-style "fg=#CDD6F4,bg=#1E1E2E"
set -g message-command-style "fg=#CDD6F4,bg=#1E1E2E"
set -g status-style "fg=#CDD6F4,bg=#1E1E2E"
set -g status-left-style "fg=#7F849C,bg=#1E1E2E"
set -g status-right "#{?pane_in_mode,#[fg=#1E1E2E#,bg=#F9E2AF#,bold] SCROLL #[default],}#{?client_prefix,#[fg=#1E1E2E#,bg=#A6E3A1#,bold] PREFIX #[default],}#{?window_zoomed_flag,#[fg=#1E1E2E#,bg=#89B4FA#,bold] ZOOM #[default],}#[fg=#7F849C] #h "
set -g window-status-style "fg=#7F849C,bg=#1E1E2E"
set -g window-status-current-style "fg=#A6E3A1,bg=#1E1E2E"
set -g window-status-activity-style "fg=#1E1E2E,bg=#F9E2AF"
set -g window-status-bell-style "fg=#1E1E2E,bg=#F38BA8"
set -g pane-border-style "fg=#7F849C"
set -g pane-active-border-style "fg=#A6E3A1"
setw -g clock-mode-colour "#A6E3A1"
