render {
  cm_enabled = true
  cm_fs_passthrough = 2
}

# GTK apps: 2x scale everywhere
env = GDK_SCALE,2

# laptop panel
monitor = eDP-1,preferred,auto,auto,cm,srgb

# external monitor
monitor = DP-3,preferred,auto,auto

# disable laptop panel when DP-3 exists
monitor = eDP-1, disable
