[colors]
draw_bold_text_with_bright_colors = true

[cursor]
style = "Underline"
thickness = 0.2

[font]
size = 16.0

[font.normal]
family = "JetBrainsMono Nerd Font"

[window]
decorations = "buttonless"
dynamic_padding = true
opacity = 0.999

[window.padding]
x = 10
y = 10

[colors.primary]
background = "#2c2e34"
foreground = "#e2e2e3"
dim_foreground = "#7f8490"
bright_foreground = "#ffffff"

[colors.selection]
text = "#eff1f5"
background = "#dc8a78"

[colors.normal]
black = "#181819"
red = "#fc5d7c"
green = "#9ed072"
yellow = "#e7c664"
blue = "#76cce0"
magenta = "#b39df3"
cyan = "#5ed5ff"
white = "#d0d0d0"

[colors.bright]
black = "#5a5a5a"
red = "#ff5370"
green = "#c3e88d"
yellow = "#ffcb6b"
blue = "#82aaff"
magenta = "#c792ea"
cyan = "#89ddff"
white = "#ffffff"

[[colors.indexed_colors]]
index = 16
color = "#fe640b"

[[colors.indexed_colors]]
index = 17
color = "#dc8a78"
