[cursor]
style = "Underline"
thickness = 0.2

[font]
size = 16.0
[font.normal]
family = "JetBrainsMono Nerd Font"

[window]
decorations = "buttonless"
dynamic_padding = true
opacity = 0.999
[window.padding]
x = 10
y = 10

[colors.primary]
background = "#161617"
foreground = "#c9c7cd"
[colors.cursor]
cursor = "#757581"
text = "#c9c7cd"
[colors.normal]
black = "#27272a"
blue = "#aca1cf"
cyan = "#ea83a5"
green = "#90b99f"
magenta = "#e29eca"
red = "#f5a191"
white = "#c1c0d4"
yellow = "#e6b99d"
[colors.bright]
black = "#353539"
blue = "#b9aeda"
cyan = "#f591b2"
green = "#9dc6ac"
magenta = "#ecaad6"
red = "#ffae9f"
white = "#cac9dd"
yellow = "#f0c5a9"
