[settings]
auto_install = true
lockfile = true
idiomatic_version_file_enable_tools = ["node", "yarn"]
node.corepack = true

[tools]
node = "22"
aws-cli = { version = "latest", symlink_bins = true }
bun = "latest"
claude = "latest"
herdr = "latest"
"npm:ntn" = "latest"
"github:k1LoW/git-wt" = "latest"
go = "latest"
golangci-lint = "latest"
opencode = "latest"
rust = "latest"
stylua = "latest"
turso = "latest"
typst = "latest"
vercel = "latest"
yarn = "latest"
zig = "latest"
