[settings]
auto_install = true
lockfile = true
idiomatic_version_file_enable_tools = ["node", "yarn"]
node.corepack = true

[tools]
node = "24"
aws-cli = { version = "latest", symlink_bins = true }
bun = "latest"
claude = "latest"
"cargo:https://github.com/reobin/herdr" = { version = "branch:reobin", install_env = { ZIG = "/Users/reobin/.local/share/mise/installs/zig/0.16.0/bin/zig" } }
"npm:ntn" = "latest"
"github:k1LoW/git-wt" = "latest"
go = "latest"
golangci-lint = "latest"
opencode = "latest"
pi = "latest"
python = "latest"
rust = "latest"
stylua = "latest"
turso = "latest"
typst = "latest"
vercel = "latest"
yarn = "4"
zig = ["latest", "0.16.0"]
