# wallpaper-color = #2A2119
palette = 0=#192330
palette = 1=#C94F6D
palette = 2=#81B29A
palette = 3=#DBC074
palette = 4=#719CD6
palette = 5=#9D79D6
palette = 6=#63CDCF
palette = 7=#DFDFE0
palette = 8=#575860
palette = 9=#D16983
palette = 10=#8EBAA4
palette = 11=#E0C989
palette = 12=#86ABDC
palette = 13=#BAA1E2
palette = 14=#7AD5D6
palette = 15=#E4E4E5
background = #192330
foreground = #CDCECF
cursor-color = #CDCECF
selection-background = #2B3B51
selection-foreground = #CDCECF
