#!/bin/bash
# omarchy:summary=Toggle single-window 12:9 aspect ratio.

ENABLED_NOTIFICATION="      Enable single-window 12:9 aspect ratio"
DISABLED_NOTIFICATION="      Disable single-window 12:9 aspect ratio"

FLAG_NAME="single-window-129"
FLAG="$HOME/.local/state/omarchy/toggles/hypr/$FLAG_NAME.conf"
FLAG_SOURCE="$HOME/.config/hypr/toggles/$FLAG_NAME.conf"

if [[ -f $FLAG ]]; then
  rm $FLAG
  [[ -n $DISABLED_NOTIFICATION ]] && notify-send -u low "$DISABLED_NOTIFICATION"
elif [[ -f $FLAG_SOURCE ]]; then
  cp $FLAG_SOURCE $FLAG
  [[ -n $ENABLED_NOTIFICATION ]] && notify-send -u low "$ENABLED_NOTIFICATION"
else
  echo "Flag not found: $FLAG_NAME"
  exit 1
fi

hyprctl reload
