set -g mode-style "bg=default,fg=default,reverse"
set -g message-style "fg=#C0CAF5,bg=#1A1B26"
set -g message-command-style "fg=#C0CAF5,bg=#1A1B26"
set -g status-style "fg=#C0CAF5,bg=#1A1B26"
set -g status-left-style "fg=#414868,bg=#1A1B26"
set -g status-right "#{?pane_in_mode,#[fg=#1A1B26#,bg=#E0AF68#,bold] SCROLL #[default],}#{?client_prefix,#[fg=#1A1B26#,bg=#9ECE6A#,bold] PREFIX #[default],}#{?window_zoomed_flag,#[fg=#1A1B26#,bg=#7AA2F7#,bold] ZOOM #[default],}#[fg=#414868] #h "
set -g window-status-style "fg=#414868,bg=#1A1B26"
set -g window-status-current-style "fg=#9ECE6A,bg=#1A1B26"
set -g window-status-activity-style "fg=#1A1B26,bg=#E0AF68"
set -g window-status-bell-style "fg=#1A1B26,bg=#F7768E"
set -g pane-border-style "fg=#414868"
set -g pane-active-border-style "fg=#9ECE6A"
setw -g clock-mode-colour "#9ECE6A"
