palette = 0=#1D211A
palette = 1=#EA938B
palette = 2=#BCCD80
palette = 3=#F7C775
palette = 4=#90DDE4
palette = 5=#DAC3ED
palette = 6=#A5D6CB
palette = 7=#FBFCF6
palette = 8=#99A293
palette = 9=#EA938B
palette = 10=#ECF6AE
palette = 11=#FBE09F
palette = 12=#90DDE4
palette = 13=#DAC3ED
palette = 14=#A5D6CB
palette = 15=#FBFCF7
background = #1D211A
foreground = #FBFCF6
cursor-color = #FBFCF7
selection-background = #616B5C
selection-foreground = #FBFCF6
