set -g mode-style "bg=default,fg=default,reverse"
set -g message-style "fg=#352C24,bg=#F6F2EE"
set -g message-command-style "fg=#352C24,bg=#F6F2EE"
set -g status-style "fg=#352C24,bg=#F6F2EE"
set -g status-left-style "fg=#7F6D5F,bg=#F6F2EE"
set -g status-right "#{?pane_in_mode,#[fg=#F6F2EE#,bg=#AC5402#,bold] SCROLL #[default],}#{?client_prefix,#[fg=#F6F2EE#,bg=#396847#,bold] PREFIX #[default],}#{?window_zoomed_flag,#[fg=#F6F2EE#,bg=#2848A9#,bold] ZOOM #[default],}#[fg=#7F6D5F] #h "
set -g window-status-style "fg=#7F6D5F,bg=#F6F2EE"
set -g window-status-current-style "fg=#396847,bg=#F6F2EE"
set -g window-status-activity-style "fg=#F6F2EE,bg=#AC5402"
set -g window-status-bell-style "fg=#F6F2EE,bg=#A5222F"
set -g pane-border-style "fg=#7F6D5F"
set -g pane-active-border-style "fg=#396847"
setw -g clock-mode-colour "#396847"
