#!/bin/sh

yay -S --noconfirm --needed gnome-calendar gnome-online-accounts gnome-online-accounts-gtk evolution-data-center

systemctl --user enable evolution-addressbook-factory.service
systemctl --user enable evolution-calendar-factory.service
systemctl --user enable evolution-source-registry.service
