#!/bin/sh

yay -S --noconfirm --needed helium-browser-bin

xdg-settings set default-web-browser helium.desktop
xdg-mime default helium.desktop text/html
xdg-mime default helium.desktop x-scheme-handler/http
xdg-mime default helium.desktop x-scheme-handler/https
xdg-mime default helium.desktop x-scheme-handler/about
xdg-mime default helium.desktop x-scheme-handler/unknown
