#!/usr/bin/env bash

set -eu

export DOTFILES_DIRECTORY="$HOME/dotfiles"
export INSTALL_DIRECTORY="$DOTFILES_DIRECTORY/omarchy"

cd "$INSTALL_DIRECTORY"

APPS=(
  stow
  keyd
  zsh
  shell
  slack-desktop
  telegram-desktop
  openvpn
  lazysql
  notion-app-electron
  bruno
  aws-cli-v2
  bind
  witr
  hyprdynamicmonitors
)

cd "$INSTALL_DIRECTORY"

for app in "${APPS[@]}"; do
  script="$INSTALL_DIRECTORY/software/$app"

  if [[ ! -f "$script" ]]; then
    echo "⚠️  Skipping $app (missing: $script)" >&2
    continue
  fi

  echo "installing $app"
  source "$script"
done
