#!/bin/sh

APPS=("stow" "keyd" "zsh" "shell" "slack-desktop" "telegram-desktop" "openvpn" "lazysql" "hyprmode")

cd $INSTALL_DIRECTORY

for app in "${APPS[@]}"; do
  . $INSTALL_DIRECTORY/software/$app
done
