#!/bin/sh

if command -v pnpm >/dev/null 2>&1; then
  :
else
  if ! command -v corepack >/dev/null 2>&1; then
    npm install -g corepack
  fi

  corepack enable
  corepack prepare pnpm@latest --activate
fi
