set -g mode-style "bg=default,fg=default,reverse"
set -g message-style "fg=#D3C6AA,bg=#2D353B"
set -g message-command-style "fg=#D3C6AA,bg=#2D353B"
set -g status-style "fg=#D3C6AA,bg=#2D353B"
set -g status-left-style "fg=#859289,bg=#2D353B"
set -g status-right "#{?pane_in_mode,#[fg=#2D353B#,bg=#DBBC7F#,bold] SCROLL #[default],}#{?client_prefix,#[fg=#2D353B#,bg=#A7C080#,bold] PREFIX #[default],}#{?window_zoomed_flag,#[fg=#2D353B#,bg=#7FBBB3#,bold] ZOOM #[default],}#[fg=#859289] #h "
set -g window-status-style "fg=#859289,bg=#2D353B"
set -g window-status-current-style "fg=#A7C080,bg=#2D353B"
set -g window-status-activity-style "fg=#2D353B,bg=#DBBC7F"
set -g window-status-bell-style "fg=#2D353B,bg=#E67E80"
set -g pane-border-style "fg=#475258"
set -g pane-active-border-style "fg=#A7C080"
setw -g clock-mode-colour "#A7C080"
