#!/bin/bash

. "$HOME/dotfiles/omarchy/dotfiles/lib"

replace_with_stow_source "$HOME/dotfiles/bash/.bashrc" "$HOME/.bashrc"
replace_with_stow_source "$HOME/dotfiles/bash/.bash_profile" "$HOME/.bash_profile"

stow bash
