#!/bin/sh

CONFIGS=("git" "keyd" "ghostty" "zsh" "starship" "nvim" "hypr")

cd $DOTFILES_DIRECTORY

for config in "${CONFIGS[@]}"; do
  echo "configuring dotfiles for $config"
  . $INSTALL_DIRECTORY/dotfiles/$config
done
