#!/bin/sh

. "$HOME/dotfiles/omarchy/dotfiles/lib"

replace_with_stow_source "$HOME/dotfiles/opencode/.config/opencode/opencode.json" "$HOME/.config/opencode/opencode.json"
replace_with_stow_source "$HOME/dotfiles/opencode/.config/opencode/tui.json" "$HOME/.config/opencode/tui.json"
replace_with_stow_source "$HOME/dotfiles/opencode/.config/opencode/themes" "$HOME/.config/opencode/themes"

sudo stow opencode
