#!/usr/bin/env bash

set -eu

DOTFILES_DIRECTORY="$HOME/dotfiles"
INSTALL_DIRECTORY="$DOTFILES_DIRECTORY/macos"

echo "requesting sudo access"
if ! sudo -v; then
  echo "sudo access is required; aborting" >&2
  exit 1
fi

echo "installing Homebrew packages"
brew bundle --file "$DOTFILES_DIRECTORY/brew/Brewfile"

echo "running macOS config"
"$INSTALL_DIRECTORY/config"

. "$INSTALL_DIRECTORY/software/install"
. "$INSTALL_DIRECTORY/dotfiles/install"
