palette = 0=#161616
palette = 1=#EE5396
palette = 2=#25BE6A
palette = 3=#08BDBA
palette = 4=#78A9FF
palette = 5=#BE95FF
palette = 6=#33B1FF
palette = 7=#F2F4F8
palette = 8=#525252
palette = 9=#FF7EB6
palette = 10=#42BE65
palette = 11=#3DDBD9
palette = 12=#82CFFF
palette = 13=#D4BBFF
palette = 14=#6FDCCE
palette = 15=#FFFFFF
background = #161616
foreground = #F2F4F8
cursor-color = #F2F4F8
selection-background = #393939
selection-foreground = #F2F4F8
