palette = 0=#0A0C10
palette = 1=#FF9492
palette = 2=#26CD4D
palette = 3=#F0B72F
palette = 4=#71B7FF
palette = 5=#CB9EFF
palette = 6=#39C5CF
palette = 7=#D9DEE3
palette = 8=#7A828E
palette = 9=#FFB1AF
palette = 10=#4AE168
palette = 11=#F7C843
palette = 12=#91CBFF
palette = 13=#DBB7FF
palette = 14=#56D4DD
palette = 15=#FFFFFF
background = #0A0C10
foreground = #F0F3F6
cursor-color = #F0F3F6
selection-background = #2F4F7F
selection-foreground = #FFFFFF
