palette = 0=#000000
palette = 1=#FF5F59
palette = 2=#44BC44
palette = 3=#D0BC00
palette = 4=#2FAFFF
palette = 5=#FEACD0
palette = 6=#00D3D0
palette = 7=#FFFFFF
palette = 8=#595959
palette = 9=#FF7F86
palette = 10=#70B900
palette = 11=#F0CE43
palette = 12=#79A8FF
palette = 13=#B6A0FF
palette = 14=#6AE4B9
palette = 15=#FFFFFF
background = #000000
foreground = #FFFFFF
cursor-color = #FFFFFF
selection-background = #5A5A5A
selection-foreground = #FFFFFF
