set -g mode-style "bg=default,fg=default,reverse"
set -g message-style "fg=#FFFFFF,bg=#000000"
set -g message-command-style "fg=#FFFFFF,bg=#000000"
set -g status-style "fg=#FFFFFF,bg=#000000"
set -g status-left-style "fg=#989898,bg=#000000"
set -g status-right "#{?pane_in_mode,#[fg=#000000#,bg=#D0BC00#,bold] SCROLL #[default],}#{?client_prefix,#[fg=#000000#,bg=#44BC44#,bold] PREFIX #[default],}#{?window_zoomed_flag,#[fg=#000000#,bg=#2FAFFF#,bold] ZOOM #[default],}#[fg=#989898] #h "
set -g window-status-style "fg=#989898,bg=#000000"
set -g window-status-current-style "fg=#70B900,bg=#000000"
set -g window-status-activity-style "fg=#000000,bg=#D0BC00"
set -g window-status-bell-style "fg=#000000,bg=#FF5F59"
set -g pane-border-style "fg=#989898"
set -g pane-active-border-style "fg=#70B900"
setw -g clock-mode-colour "#70B900"
