# Extra autostart processes
# exec-once = uwsm-app -- my-service

# Startup layout
exec-once = [workspace 1 silent] omarchy launch browser
exec-once = [workspace 2 silent] uwsm-app -- xdg-terminal-exec tmux new-session -A
exec-once = [workspace 10 silent] omarchy launch webapp "https://mail.proton.me/u/1/inbox"
