general {
    lock_cmd = omarchy-lock-screen                         # lock screen and 1password
    before_sleep_cmd = loginctl lock-session               # lock before suspend.
    after_sleep_cmd = sleep 1 && hyprctl dispatch dpms on  # delay for PAM readiness, then turn on display.
    inhibit_sleep = 3                                      # wait until screen is locked
}

listener {
    timeout = 300                                             # 5min
    on-timeout = pidof hyprlock || omarchy-launch-screensaver # start screensaver (if we haven't locked already)
}

listener {
    timeout = 3600                     # 1h
    on-timeout = loginctl lock-session # lock screen after 1 hour
}

listener {
    timeout = 3610                                           # 1h + 10s (avoid race with lock)
    on-timeout = pidof hyprlock && hyprctl dispatch dpms off # screen off after lock engages
    on-resume = hyprctl dispatch dpms on                     # screen on when activity is detected
}
