input {
  kb_layout = us,ca
  kb_variant = ,fr
  kb_options = grp:rctrl_toggle

  repeat_rate = 40
  repeat_delay = 600

  touchpad {
    scroll_factor = 0.4

    # invert scroll direction
    natural_scroll = true

    # disable tap gestures, require a press
    tap-to-click = false

    # 1 finger = left click, 2 fingers = right click, 3 = middle
    clickfinger_behavior = true
  }
}

# scroll nicely in the terminal
windowrule = match:class (Alacritty|kitty), scroll_touchpad 1.5
windowrule = match:class com.mitchellh.ghostty, scroll_touchpad 0.2
