windowrule = tag +floating-window, match:class ^([Pp]roton-authenticator)$

windowrule = float on, match:class ^org\.omarchy\.cliamp$
windowrule = size 50% 50%, match:class ^org\.omarchy\.cliamp$
windowrule = center on, match:class ^org\.omarchy\.cliamp$
windowrule = workspace special:scratchpad, match:class ^org\.omarchy\.cliamp$
