windowrule = tag +floating-window, match:class ^([Pp]roton-authenticator)$
windowrule = rounding 0, match:float 1
windowrule = rounding 0, match:tag pop

windowrule = float on, match:class ^org\.omarchy\.cliamp$
windowrule = size 50% 50%, match:class ^org\.omarchy\.cliamp$
windowrule = center on, match:class ^org\.omarchy\.cliamp$
windowrule = workspace special:scratchpad, match:class ^org\.omarchy\.cliamp$
