#!/usr/bin/env bash

rm -rf ~/.config/terminal-theme ~/.config/tt

stow tt

mkdir -p ~/.config/tt/active ~/.config/ghostty/themes
rm -f ~/.config/ghostty/themes/terminal-active
cp ~/.config/tt/themes/carbonfox/ghostty.conf ~/.config/tt/active/ghostty.conf
cp ~/.config/tt/themes/carbonfox/nvim.lua ~/.config/tt/active/nvim.lua
cp ~/.config/tt/themes/carbonfox/ghostty.conf ~/.config/ghostty/themes/terminal-active
printf 'carbonfox\n' > ~/.config/tt/current
