set -g mode-style "bg=default,fg=default,reverse"
set -g message-style "fg=#4C4F69,bg=#EFF1F5"
set -g message-command-style "fg=#4C4F69,bg=#EFF1F5"
set -g status-style "fg=#4C4F69,bg=#EFF1F5"
set -g status-left-style "fg=#7C7F93,bg=#EFF1F5"
set -g status-right "#{?pane_in_mode,#[fg=#EFF1F5#,bg=#DF8E1D#,bold] SCROLL #[default],}#{?client_prefix,#[fg=#EFF1F5#,bg=#40A02B#,bold] PREFIX #[default],}#{?window_zoomed_flag,#[fg=#EFF1F5#,bg=#1E66F5#,bold] ZOOM #[default],}#[fg=#7C7F93] #h "
set -g window-status-style "fg=#7C7F93,bg=#EFF1F5"
set -g window-status-current-style "fg=#40A02B,bg=#EFF1F5"
set -g window-status-activity-style "fg=#EFF1F5,bg=#DF8E1D"
set -g window-status-bell-style "fg=#EFF1F5,bg=#D20F39"
set -g pane-border-style "fg=#7C7F93"
set -g pane-active-border-style "fg=#40A02B"
setw -g clock-mode-colour "#40A02B"
