# wallpaper-color = #9F9F99
palette = 0=#F2F1EF
palette = 1=#C84053
palette = 2=#6F894E
palette = 3=#77713F
palette = 4=#4D699B
palette = 5=#B35B79
palette = 6=#597B75
palette = 7=#22262D
palette = 8=#E2E1DF
palette = 9=#D7474B
palette = 10=#6E915F
palette = 11=#836F4A
palette = 12=#6693BF
palette = 13=#624C83
palette = 14=#5E857A
palette = 15=#43436C
background = #F2F1EF
foreground = #22262D
cursor-color = #22262D
selection-background = #E2E1DF
selection-foreground = #22262D
