set -g mode-style "bg=default,fg=default,reverse"
set -g message-style "fg=#ABB2BF,bg=#1E2127"
set -g message-command-style "fg=#ABB2BF,bg=#1E2127"
set -g status-style "fg=#ABB2BF,bg=#1E2127"
set -g status-left-style "fg=#5C6370,bg=#1E2127"
set -g status-right "#{?pane_in_mode,#[fg=#1E2127#,bg=#E5C07B#,bold] SCROLL #[default],}#{?client_prefix,#[fg=#1E2127#,bg=#98C379#,bold] PREFIX #[default],}#{?window_zoomed_flag,#[fg=#1E2127#,bg=#61AFEF#,bold] ZOOM #[default],}#[fg=#5C6370] #h "
set -g window-status-style "fg=#5C6370,bg=#1E2127"
set -g window-status-current-style "fg=#98C379,bg=#1E2127"
set -g window-status-activity-style "fg=#1E2127,bg=#E5C07B"
set -g window-status-bell-style "fg=#1E2127,bg=#E06C75"
set -g pane-border-style "fg=#5C6370"
set -g pane-active-border-style "fg=#98C379"
setw -g clock-mode-colour "#98C379"
