# wallpaper-color = #3D3B2F
palette = 0=#272822
palette = 1=#F92672
palette = 2=#A6E22E
palette = 3=#F4BF75
palette = 4=#66D9EF
palette = 5=#AE81FF
palette = 6=#A1EFE4
palette = 7=#F8F8F2
palette = 8=#75715E
palette = 9=#F92672
palette = 10=#A6E22E
palette = 11=#E6DB74
palette = 12=#66D9EF
palette = 13=#AE81FF
palette = 14=#A1EFE4
palette = 15=#F9F8F5
background = #272822
foreground = #F8F8F2
cursor-color = #F8F8F2
selection-background = #49483E
selection-foreground = #F8F8F2
