set -g mode-style "bg=default,fg=default,reverse"
set -g message-style "fg=#D9D9D9,bg=#4B4B4B"
set -g message-command-style "fg=#D9D9D9,bg=#4B4B4B"
set -g status-style "fg=#D9D9D9,bg=#4B4B4B"
set -g status-left-style "fg=#757575,bg=#4B4B4B"
set -g status-right "#{?pane_in_mode,#[fg=#4B4B4B#,bg=#DFBC72#,bold] SCROLL #[default],}#{?client_prefix,#[fg=#4B4B4B#,bg=#98BC99#,bold] PREFIX #[default],}#{?window_zoomed_flag,#[fg=#4B4B4B#,bg=#98BEDE#,bold] ZOOM #[default],}#[fg=#757575] #h "
set -g window-status-style "fg=#757575,bg=#4B4B4B"
set -g window-status-current-style "fg=#BCDDBD,bg=#4B4B4B"
set -g window-status-activity-style "fg=#4B4B4B,bg=#DFBC72"
set -g window-status-bell-style "fg=#4B4B4B,bg=#E12672"
set -g pane-border-style "fg=#757575"
set -g pane-active-border-style "fg=#BCDDBD"
setw -g clock-mode-colour "#BCDDBD"
