palette = 0=#21222C
palette = 1=#FF5555
palette = 2=#50FA7B
palette = 3=#F1FA8C
palette = 4=#BD93F9
palette = 5=#FF79C6
palette = 6=#8BE9FD
palette = 7=#F8F8F2
palette = 8=#6272A4
palette = 9=#FF6E6E
palette = 10=#69FF94
palette = 11=#FFFFA5
palette = 12=#D6ACFF
palette = 13=#FF92DF
palette = 14=#A4FFFF
palette = 15=#FFFFFF
background = #282A36
foreground = #F8F8F2
cursor-color = #F8F8F2
selection-background = #44475A
selection-foreground = #F8F8F2
